# Generated by Django 5.1.3 on 2024-12-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_second_user_alter_user_task_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtask',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
